# Generated by Django 4.2.6 on 2024-04-06 07:11

import course.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelManagers(
            name='usermaster',
            managers=[
                ('objects', course.manager.CustomBaseUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usermaster',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
